name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 10.x

      - name: Install NPM modules
        run: npm ci
        working-directory: ./tools

      - name: Run CI tests
        run: npm test
        working-directory: ./tools
